version: '3.8'

name: ms-online-course-dev

services:
  gateway:
    build:
      context: ./gateway
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./gateway:/app
    env_file:
      - .env

  course:
    build:
      context: ./course
      target: dev
    ports:
      - "3001:3001"
    volumes:
      - ./course:/app
    env_file:
      - .env

  enrollment:
    build:
      context: ./enrollment
      target: dev
    ports:
      - "3002:3002"
    volumes:
      - ./enrollment:/app
    env_file:
      - .env

  user:
    build:
      context: ./user
      target: dev
    ports:
      - "3003:3003"
    volumes:
      - ./user:/app
    env_file:
      - .env

  auth:
    build:
      context: ./auth
      target: dev
    ports:
      - "3004:3004"
    volumes:
      - ./auth:/app
    env_file:
      - .env

  

  
