version: '3.8'

name: ms-online-course-dev

services:
  gateway:
    build:
      context: ./gateway
      target: dev
      args:
        - PORT=${GATEWAY_PORT}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    volumes:
      - ./gateway:/app
    env_file:
      - .env
    depends_on:
      - course
      - enrollment
      - user
      - auth

  course:
    build:
      context: ./course
      target: dev
      args:
        - PORT=${COURSE_SERVICE_PORT}
    ports:
      - "${COURSE_SERVICE_PORT}:${COURSE_SERVICE_PORT}"
    volumes:
      - ./course:/app
    env_file:
      - .env

  enrollment:
    build:
      context: ./enrollment
      target: dev
      args:
        - PORT=${ENROLLMENT_SERVICE_PORT}
    ports:
      - "${ENROLLMENT_SERVICE_PORT}:${ENROLLMENT_SERVICE_PORT}"
    volumes:
      - ./enrollment:/app
    env_file:
      - .env

  user:
    build:
      context: ./user
      target: dev
      args:
        - PORT=${USER_SERVICE_PORT}
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    volumes:
      - ./user:/app
    env_file:
      - .env

  auth:
    build:
      context: ./auth
      target: dev
      args:
        - PORT=${AUTH_SERVICE_PORT}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    volumes:
      - ./auth:/app
    env_file:
      - .env

  

  
